version: '3'

services:
  matmul-api:
    build: ./
    container_name: matmul-api
    volumes:
      - "./:/usr/src/app"
    working_dir: "/usr/src/app"
    ports:
      - "8007:8000"
    restart: always